// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_nrgLH54l7h8JNNDxuwxJVi0NtC8aSk',
    appId: '1:528802576361:web:1ee441d34987f83e847d78',
    messagingSenderId: '528802576361',
    projectId: 'food-snap-40170',
    authDomain: 'food-snap-40170.firebaseapp.com',
    storageBucket: 'food-snap-40170.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmAn-2-iKPv0nWnQDTPkItFm5XwMkUsI0',
    appId: '1:528802576361:android:e28953d0d733815a847d78',
    messagingSenderId: '528802576361',
    projectId: 'food-snap-40170',
    storageBucket: 'food-snap-40170.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbzpcKQ6_-Klb60_Mvdiu2JKBedVgk7oI',
    appId: '1:528802576361:ios:fd4fc26c6d410b6c847d78',
    messagingSenderId: '528802576361',
    projectId: 'food-snap-40170',
    storageBucket: 'food-snap-40170.firebasestorage.app',
    iosBundleId: 'com.example.foodsnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbzpcKQ6_-Klb60_Mvdiu2JKBedVgk7oI',
    appId: '1:528802576361:ios:fd4fc26c6d410b6c847d78',
    messagingSenderId: '528802576361',
    projectId: 'food-snap-40170',
    storageBucket: 'food-snap-40170.firebasestorage.app',
    iosBundleId: 'com.example.foodsnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb_nrgLH54l7h8JNNDxuwxJVi0NtC8aSk',
    appId: '1:528802576361:web:9f03618c22469ae1847d78',
    messagingSenderId: '528802576361',
    projectId: 'food-snap-40170',
    authDomain: 'food-snap-40170.firebaseapp.com',
    storageBucket: 'food-snap-40170.firebasestorage.app',
  );
}
